apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zbpyqc2ld-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zbpyqc2ld-nodejs 
  name: zbpyqc2ld-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zbpyqc2ld-nodejs 
